bookshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('', include('pages.urls')),
    path('api/', include('city.urls')),
    path('photo/', include('photoapp.urls')),
    path('work/', include('tutorial1.urls')),
    path('list/', include('administration.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

city/urls.py
# api/urls.py
from django.urls import path
from . import views
from .views import BookList, BookDetail, CityList, GradeList, SchoolList


urlpatterns = [
    path('book/', BookList.as_view()),
    path('book/<int:pk>/', BookDetail.as_view()),

    path('city/', CityList.as_view()),
    path('grade/', GradeList.as_view()),
    path('school/', SchoolList.as_view()),

    path('city_list/', views.city_list, name='city_list'),
    path('school_list/', views.school_list, name='school_list'),
    path('grade_list/', views.grade_list, name='grade_list'),
    path('all_list/', views.all_list, name='all_list'),
    path('click_all_list/', views.click_all_list, name='click_all_list'),
    path('updateSchoolGradeGroup/', views.updateSchoolGradeGroup, name='updateSchoolGradeGroup'),
    path('updateGradeBox/', views.updateGradeBox, name='updateGradeBox'),
    path('book_List/', views.book_List, name='book_List'),
    path('decrement/', views.decrement, name='decrement'),
    path('increment/', views.increment, name='increment'),
]

photoapp/urls.py
'''Photoapp URL patterns'''

from django.urls import path

from .views import (
    AllPhotoListView,
    MyPhotoListView,
    PhotoTagListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView
)

app_name = 'photo'

urlpatterns = [
    path('', AllPhotoListView.as_view(), name='alllist'),
    path('mylist', MyPhotoListView.as_view(), name='mylist'),
    path('tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),
    path('<int:pk>/', PhotoDetailView.as_view(), name='detail'),
    path('create/', PhotoCreateView.as_view(), name='create'),
    path('<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),
]

tutorial1/urls.py
'''Workapp URL patterns'''

from django.urls import path

from .views import (
    AllWorkListView,
    FilteredWorkListView,
    MyWorkListView,
    WorkTagListView,
    WorkDetailView,
)

app_name = 'work'

urlpatterns = [
    path('', AllWorkListView.as_view(), name='alllist'),
    path('mylist', MyWorkListView.as_view(), name='mylist'),
    path('mylist1', FilteredWorkListView.as_view(), name='mylist1'),
    path('tag/<slug:tag>/', WorkTagListView.as_view(), name='tag'),
    path('<int:pk>/', WorkDetailView.as_view(), name='detail'),
]

tutorial1/models.py
'''Tutorial1 Models'''

from django.db import models
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from django.core.validators import FileExtensionValidator 
import datetime

SCHOOL_OPTIONS = (
    ('lmc','LMC'),
    ('sfc', 'SFC'),
    ('cms','CMS'),
    ('mbic','MBIC'),
)

GRADE_OPTIONS = (
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),
    ('9','9'),
    ('10','10'),
    ('11','11'),
    ('12','12'),
)

SUBJECT_OPTIONS = (
    ('English','Eng'),
    ('Hindi','Hin'),
    ('Mathematics','Maths'),
    ('Computer','Comp'),
)

TYPE_OPTIONS = (
    ('Classwork','CW'),
    ('Homework','HW'),
)

class Work(models.Model):
    
    title = models.CharField(max_length=45)
    
    description = models.CharField(max_length=250)

    created = models.DateTimeField(auto_now_add=True)

    workfile = models.FileField(upload_to='work/')

    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    school = models.CharField(max_length=6, choices=SCHOOL_OPTIONS, default='CMS')
    grade = models.CharField(max_length=4, choices=GRADE_OPTIONS, default='1')
    subject = models.CharField(max_length=20, choices=SUBJECT_OPTIONS, default='English')
    type = models.CharField(max_length=10, choices=TYPE_OPTIONS, default='HW')
    dateOfAssignment = models.DateField(default=datetime.date.today)

    tags = TaggableManager() 

    def __str__(self):
        return self.title

tutorial1/views.py
'''Works app generic views'''

from django import forms
from django.shortcuts import get_object_or_404, HttpResponse, Http404
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from . import views
from django.views import View
from .pdfcreator import renderPdf
from django_tables2 import SingleTableView, SingleTableMixin


from django_filters.views import FilterView
from django_filters import FilterSet, CharFilter, ChoiceFilter, DateFilter


from .models import Work
from .tables import WorkTable

SCHOOL_CHOICES = (
    ('lmc','LMC'),
    ('sfc', 'SFC'),
    ('cms','CMS'),
    ('mbic','MBIC'),
)

GRADE_CHOICES = (
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),
    ('9','9'),
    ('10','10'),
    ('11','11'),
    ('12','12'),
)

SUBJECT_CHOICES = (
    ('English','Eng'),
    ('Hindi','Hin'),
    ('Mathematics','Maths'),
    ('Computer','Comp'),
)

class DateInput(forms.DateInput):
    input_type = 'date'

class WorkFilter(FilterSet):
    subject = ChoiceFilter(choices=SUBJECT_CHOICES)
    grade = ChoiceFilter(choices=GRADE_CHOICES, empty_label=None)
    school = ChoiceFilter(choices=SCHOOL_CHOICES, empty_label=None)
    dateOfAssignment = DateFilter(widget=DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Work
        fields = {"dateOfAssignment": ["exact"], "school": ["exact"], "grade": ["exact"], "subject": ["exact"],}

class FilteredWorkListView(SingleTableMixin, FilterView):
    table_class = WorkTable
    model = Work
    template_name = "tutorial1/mylist.html"
    filterset_class = WorkFilter


class AllWorkListView(SingleTableView):
    model = Work
    table_class = WorkTable
    template_name = 'tutorial1/alllist.html'
    # context_object_name = 'photos'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['works'] = Work.objects.all()
        
        print("context", context)
        return context
    
class MyWorkListView(SingleTableView):
    model = Work     
    table_class = WorkTable
    template_name = 'tutorial1/mylist.html'
    # context_object_name = 'photos'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['works'] = Work.objects.all().filter(submitter=self.request.user)
        print("context", context)
        return context


class WorkTagListView(AllWorkListView): 
    template_name = 'tutorial1/taglist.html'
    # Custom function
    def get_tag(self):
        return self.kwargs.get('tag')
    def get_queryset(self):
        return self.model.objects.filter(tags__slug=self.get_tag())
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.get_tag()
        return context
     

class WorkDetailView(DetailView):
    model = Work
    template_name = 'tutorial1/detail.html'
    context_object_name = 'work'

tutorial1/templates/tutorial1/alllist.html
{% extends '_base.html' %} 
{% load render_table from django_tables2 %}

{% block content %}

<h3>All Works</h3>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

{% render_table table %}

{% endblock content %}

tutorial1/templates/tutorial1/create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Add Photo</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Add Photo</button>
  </form>
</div>
{% endblock content %}

tutorial1/templates/tutorial1/delete.html
{% extends '_base.html' %} 

{% block content %}
<div class="form-group mx-auto">
  <h2 class="text-center">
    You are going to <span class="text-danger">delete</span>: "<i
      >{{ photo }}</i
    >
    "
  </h2>
  <p class="text-center">Are you sure, you want to delete the photo ?</p>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'photo:detail' photo.id %}" class="btn btn-primary"
            >Cancel</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
      <p>This action is irreversible</p>
    </form>
  </div>
</div>

{% endblock content %}

tutorial1/templates/tutorial1/detail.html
{% extends '_base.html' %} 

{% block content %}
<div class="mx-auto">
  <h1 class="text-center">{{ work.title }}</h1>
  <p class="text-center fw-light">Uploaded on: {{work.created}} <br> By {{work.submitter.username}}</p>
  {% if user == work.submitter %}
    <p class="text-center">
      <span><a href="{% url 'work:update' work.id %}" class="text-primary px-2">Update</a></span>
      <span><a href="{% url 'work:delete' work.id %}" class="text-danger px-2">Delete</a></span>
    </p>
  {% endif %}
</div>
<div class="row pb-5">
  <div class="col-md-8">
    <img src="{{work.workfile.url}}" alt="" class="img-fluid rounded" style="width:400px;" style='border:2px solid #000000' />
  </div>
  <div class="col-md-4">
    <h4>More about this work:</h4>
    <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
      {% for tag in work.tags.all %}
        <li><a href="{% url 'work:tag' tag.slug %}" class="btn btn-sm list-group-item list-group-item-primary">{{tag.name}}</a></li>
      {% endfor %}
    </ul>
    <p>{{ work.description }}</p>
  </div>
</div>

<form>
  <input type="text" name = "comment">Add Comment</input>
  <button type = "submit">Submit</button>
</form>

{% endblock content %}

tutorial1/templates/tutorial1/list.html
{% extends '_base.html' %} 

{% block content %}

<h3>Works</h3>

<br>


<br>

<div class="row">
  {% for work in works %}
  
  <div class="col-lg-3 col-md-4 col-xs-6">
    <div class="ui card">
    <a href="{% url 'work:detail' work.id %}" class="d-block mb-4 h-100">
      <img src="{{work.workfile.url}}" class="img-fluid rounded" alt="{{work.title}}" style="width:100px;height:100px;" style='border:2px solid #000000' />
    </a>
    <!-- <h5>{{ work.title }}</h5> -->
    <!-- <h5>{{ work.school }} - {{ work.grade }}</h5> -->
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

tutorial1/templates/tutorial1/mylist.html
{% extends '_base.html' %} 
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block content %}

<h3>My works</h3>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

{% if filter %}
    <form action="" method="get" class="form form-inline">
        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'filter' %}
    </form>
{% endif %}
{% render_table table 'django_tables2/bootstrap.html' %}

{% endblock content %}

tutorial1/templates/tutorial1/pdf.html
<!DOCTYPE html>
<html>
<head>
	<title>Homework Classwork</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body>
	<div class="container">
		<div class="row justify-content-md-center">
	        <div class="col-md-12 cart_info">
		        <div class="ordered-info">
		                <img src="{{ pic1 }}"></img>
                        <img src="{{ pic2 }}"></img>
		        </div>
	        </div>
		</div>
	</div> 
</body>
</html>

tutorial1/templates/tutorial1/taglist.html
{% extends 'photoapp/list.html' %}

{% block content %}

<div class="alert alert-primary">
    <h2 class="text-center">Works with the tag {{tag}}</h2>
</div>

{{ block.super }}

{% endblock content %}

tutorial1/templates/tutorial1/update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Edit photo {{photo}}</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
  </form>
</div>
{% endblock content %}