bookshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('', include('pages.urls')),
    path('api/', include('city.urls')),
    path('photo/', include('photoapp.urls')),
    path('work/', include('tutorial1.urls')),
    path('list/', include('administration.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

city/urls.py
# api/urls.py
from django.urls import path
from . import views
from .views import BookList, BookDetail, CityList, GradeList, SchoolList


urlpatterns = [
    path('book/', BookList.as_view()),
    path('book/<int:pk>/', BookDetail.as_view()),

    path('city/', CityList.as_view()),
    path('grade/', GradeList.as_view()),
    path('school/', SchoolList.as_view()),

    path('city_list/', views.city_list, name='city_list'),
    path('school_list/', views.school_list, name='school_list'),
    path('grade_list/', views.grade_list, name='grade_list'),
    path('all_list/', views.all_list, name='all_list'),
    path('click_all_list/', views.click_all_list, name='click_all_list'),
    path('updateSchoolGradeGroup/', views.updateSchoolGradeGroup, name='updateSchoolGradeGroup'),
    path('updateGradeBox/', views.updateGradeBox, name='updateGradeBox'),
    path('book_List/', views.book_List, name='book_List'),
    path('decrement/', views.decrement, name='decrement'),
    path('increment/', views.increment, name='increment'),
]

tutorial1/urls.py
'''Workapp URL patterns'''

from django.urls import path

from .views import (
    AllWorkListView,
    FilteredWorkListView,
    MyWorkListView,
    WorkTagListView,
    WorkDetailView,
)

app_name = 'work'

urlpatterns = [
    path('', AllWorkListView.as_view(), name='alllist'),
    path('mylist', MyWorkListView.as_view(), name='mylist'),
    path('mylist1', FilteredWorkListView.as_view(), name='mylist1'),
    path('tag/<slug:tag>/', WorkTagListView.as_view(), name='tag'),
    path('<int:pk>/', WorkDetailView.as_view(), name='detail'),
]

bookshop/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Bookstore{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">-->
        <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">-->
        <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>-->
        <script src="https://kit.fontawesome.com/a0460cda06.js" crossorigin="anonymous"></script>

        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
        <!-- <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script> -->

        <!--***********HTMX CDN ************** added by Pankaj on 16 Mar 2024-->
        <script src="https://unpkg.com/htmx.org@1.9.11" integrity="sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0" crossorigin="anonymous"></script>

        <style>
            /* Custom CSS for changing Navbar color */
            .custom-navbar .navbar-nav .nav-link {
              color: #61d017; /* Change the color of Navbar links */
              font-size: 100px;
            }
         
            .custom-navbar .navbar { 
              background-color: #0d6efd; /* Change the background color of Navbar */
            }

            .p { 
                margin-bottom:0em;
            }

        </style>
        
    </head>
    
    <body>

    <!-- This was added by PANKAJ on 28 Feb 2024 from Bootstrap website to right align login page-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/file.png' %}"  width="150" height="50" class="navbar-brand-img" /></a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}" style="font-size:17px">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'services' %}" style="font-size:17px">Services</a>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:17px">
                            Countries
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">UK</a>
                            <a class="dropdown-item" href="#">Ireland</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Canada</a>
                        </div>
                        </li>
                    </ul>

                    <ul class="navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="nav-item p-2 text-dark"> <a class="nav-link" href="{% url 'status-list' user.pk %}"><i class="fa-solid fa-cart-shopping"></i> Cart</a></li>
                            <li class="nav-item p-2 text-dark"> <a class="nav-link" href="{% url 'account_logout' %}"><span class="fa-solid fa-sign-out"></span> Logout</a></li>
                        {% else %}
                            <li class="nav-item p-2 text-dark"> <a class="nav-link" href="{% url 'account_signup' %}"><span class="fa-solid fa-user"></span> Sign Up</a></li>
                            <li class="nav-item p-2 text-dark"> <a class="nav-link" href="{% url 'account_login' %}"><span class="fa-solid fa-right-to-bracket"></span> Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- This is second Nav bar (user bar) after login-->
        {% if user.is_authenticated %}
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'work:mylist' %}">My Works</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'work:alllist' %}">All Works</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        {% else %}
        {% endif %}

        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>

        <!-- JavaScript -->

        <link
        async
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/semantic-ui@2/dist/semantic.min.css"
        />
        <script src="https://cdn.jsdelivr.net/npm/semantic-ui-react/dist/umd/semantic-ui-react.min.js"></script>

        {% block javascript %}
            
            <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
           <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> -->
            <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>

        {% endblock javascript %}
    </body>
</html>

bookshop/templates/about.html
<!-- templates/about.html -->
{% extends '_base.html' %}
{% block title %}About{% endblock title %}
{% block content %}
    <h2>About Page</h2>
{% endblock content %}

{% if status.statusClient == user %}
<p>Updated on {{ status.statusDate }}</p>
<p>{{ status.statusText }}</p> <br /> <br />
{% endif %}

bookshop/templates/all_list.html
  <label >City-All</label>
  <select id="cities" name="city" hx-get="api/school_list/" hx-target="#schools" hx-trigger="changed">
    {% for city in cities %}
      <option>{{city}}</option>
    {% endfor %}
  </select>

  <label >School-All</label>
  <select id="schools" name="school" hx-get="api/grade_list/" hx-target="#grades">
    {% for school in schools %}
      <option>{{school}}</option>
    {% endfor %}
  </select>

  <label >Grade-All</label>
  <select id="grades" name="grade">
    {% for grade in grades %}
      <option>{{grade}}</option>
    {% endfor %}
  </select>

bookshop/templates/book_List.html
<p>City: {{city}}</p>
<p>School: {{school}}</p>
<p>Grade: {{grade}}</p>

    <table class="table table-hover" id="table-main">
        <thead class="text-center" id="table-head">
            <tr>
                <th scope="col">#</th>
                <th scope="col" style="width: 250px">Name</th>
                <th scope="col" style="width: 250">Qty</th>
                <th scope="col">Price</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody class="text-center" id="table-body">
            
            {% for book in books %}

                    <tr>
                        <td>{{ book.pk }}</td>
                        <td>{{ book.name }}</td>
                        <td>
                            <i hx-get="api/decrement/"
                            hx-trigger="click"
                            hx-target="#{{ book.name }}"
                            hx-swap="innerHTML"
                            hx-vals="js:{quantity: document.getElementById('{{ book.name }}').value}"
                            class="fa fa-minus" aria-hidden="true"></i>
                            <input class="ui input" type="number" id="{{ book.name }}" name="{{ book.name }}" style="width: 30px" value=1></input>
                            <i hx-get="api/increment/"
                            hx-trigger="click"
                            hx-target="#{{ book.name }}"
                            hx-swap="innerHTML"
                            hx-vals="js:{quantity: document.getElementById('{{ book.name }}').value}"
                            class="fa fa-plus" aria-hidden="true"></i>
                        </td>
                        <td>Price</td>
                        <td>Remove</td>
                    </tr>
                
            {% endfor %}
        </tbody>
    </table>

bookshop/templates/city_list.html
{% for city in cities %}
  <option>{{city}}</option>
{% endfor %}

bookshop/templates/click_all_list.html
<label for ="cityBoxid">Cities</label>
<select id="cityBoxid" name="cityBoxName" hx-get="api/updateSchoolGradeGroup/" hx-target="#schoolGradeForm2Div">
  {% for city in cities %}
    <option>{{city}}</option>
  {% endfor %}
</select>

<div id="schoolGradeForm2Div">
    <label for="schoolBoxid">Schools</label>
    <select id="schoolBoxid" name="schoolBoxName" hx-get="api/updateGradeBox/" hx-target="#gradeForm2Div">
    {% for school in schools %}
        <option>{{school}}</option>
    {% endfor %}
    </select>

    <div id="gradeForm2Div">
      <label for="gradeBoxid">Grades</label>
      <select id="gradeBoxid" name="gradeBoxName">
      {% for grade in grades %}
          <option>{{grade}}</option>
      {% endfor %}
      </select>
    </div>
    
</div>

bookshop/templates/decrement.html
<input value={{newQuantity}}></input>

bookshop/templates/grade_list.html
<select id="grades" name="grade">
{% for grade in grades %}
  <option>{{grade}}</option>
{% endfor %}
</select>

bookshop/templates/home.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}
    <h2>Homepage</h2>
    {% if user.is_authenticated %}
        Hi {{ user.email }}!
        </br>

        <button hx-get="api/click_all_list/"
            hx-trigger="click"
            hx-target="#citySchoolGradeForm2Div"
            hx-swap="innerHTML"
            class="ui button">
            CSG Form!
            </button>

        <!--This is form 2-->
        <form id="form2" hx-get="api/book_List/"
        hx-trigger="click"
        hx-target="#bookList"
        hx-swap="innerHTML">
            </br>
        
            <div id="citySchoolGradeForm2Div">
                <div id="schoolGradeForm2Div">
                    <div id="gradeForm2Div">
                    </div>
                </div>        
            </div>

        </form>


        
        <div id="bookList">

        </div>

    {% else %}
        <p>You are not logged in</p>
    {% endif %}
{% endblock content %}

bookshop/templates/school_list.html
<select id="schools" name="school" hx-get="api/grade_list/" hx-target="#grades">
{% for school in schools %}
  <option>{{school}}</option>
{% endfor %}
</select>

<select id="grades" name="grade">
  {% for grade in grades %}
    <option>{{grade}}</option>
  {% endfor %}
  </select>

bookshop/templates/services.html
<!-- templates/about.html -->
{% extends '_base.html' %}
{% block title %}Services{% endblock title %}
{% block content %}
    <h2>Services Page</h2>
{% endblock content %}

{% if status.statusClient == user %}
<p>Updated on {{ status.statusDate }}</p>
<p>{{ status.statusText }}</p> <br /> <br />
{% endif %}

bookshop/templates/status_list.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Status List{% endblock title %}

{% block content %}
    <h2>Status List</h2> <br />
    
    {% if user.is_authenticated %}
        <h4> Hello {{ user.email }} </h4> <br />
        {% for status in object_list %}
            {% if status.statusClient == user %}
                <p>Updated on {{ status.statusDate }}</p>
                <p>{{ status.statusText }}</p> <br /> <br />
            {% endif %} 
        {% endfor %}
    {% else %}
        <p>You are not logged in</p>
    {% endif %}
{% endblock content %}

bookshop/templates/updateGradeBox.html
<label for="gradeBoxid">Grades</label>
<select id="gradeBoxid" name="gradeBoxName">
    {% for grade in grades %}
        <option>{{grade}}</option>
    {% endfor %}
</select>

bookshop/templates/updateSchoolGradeGroup.html
    <label for="schoolBoxid">Schools</label>
    <select id="schoolBoxid" name="schoolBoxName" hx-get="api/updateGradeBox/" hx-target="#gradeForm2Div">
    {% for school in schools %}
        <option>{{school}}</option>
    {% endfor %}
    </select>

    <div id="gradeForm2Div">
        <label for="gradeBoxid">Grades</label>
        <select id="gradeBoxid" name="gradeBoxName">
        {% for grade in grades %}
            <option>{{grade}}</option>
        {% endfor %}
        </select>
    </div>