bookshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('', include('pages.urls')),
    path('api/', include('city.urls')),
    path('photo/', include('photoapp.urls')),
    path('work/', include('tutorial1.urls')),
    path('list/', include('administration.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

city/urls.py
# api/urls.py
from django.urls import path
from . import views
from .views import BookList, BookDetail, CityList, GradeList, SchoolList


urlpatterns = [
    path('book/', BookList.as_view()),
    path('book/<int:pk>/', BookDetail.as_view()),

    path('city/', CityList.as_view()),
    path('grade/', GradeList.as_view()),
    path('school/', SchoolList.as_view()),

    path('city_list/', views.city_list, name='city_list'),
    path('school_list/', views.school_list, name='school_list'),
    path('grade_list/', views.grade_list, name='grade_list'),
    path('all_list/', views.all_list, name='all_list'),
    path('click_all_list/', views.click_all_list, name='click_all_list'),
    path('updateSchoolGradeGroup/', views.updateSchoolGradeGroup, name='updateSchoolGradeGroup'),
    path('updateGradeBox/', views.updateGradeBox, name='updateGradeBox'),
    path('book_List/', views.book_List, name='book_List'),
    path('decrement/', views.decrement, name='decrement'),
    path('increment/', views.increment, name='increment'),
]

photoapp/urls.py
'''Photoapp URL patterns'''

from django.urls import path

from .views import (
    AllPhotoListView,
    MyPhotoListView,
    PhotoTagListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView
)

app_name = 'photo'

urlpatterns = [
    path('', AllPhotoListView.as_view(), name='alllist'),
    path('mylist', MyPhotoListView.as_view(), name='mylist'),
    path('tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),
    path('<int:pk>/', PhotoDetailView.as_view(), name='detail'),
    path('create/', PhotoCreateView.as_view(), name='create'),
    path('<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),
]

photoapp/models.py
'''Photoapp Models'''

from django.db import models
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from django.core.validators import FileExtensionValidator 
import datetime

SCHOOL_CHOICES = (
    ('lmc','LMC'),
    ('sfc', 'SFC'),
    ('cms','CMS'),
    ('mbic','MBIC'),
)

GRADE_CHOICES = (
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),
    ('9','9'),
    ('10','10'),
    ('11','11'),
    ('12','12'),
)

SUBJECT_CHOICES = (
    ('English','Eng'),
    ('Hindi','Hin'),
    ('Mathematics','Maths'),
    ('Computer','Comp'),
)

TYPE_CHOICES = (
    ('Classwork','CW'),
    ('Homework','HW'),
)

class Photo(models.Model):
    
    title = models.CharField(max_length=45)
    
    description = models.CharField(max_length=250)

    created = models.DateTimeField(auto_now_add=True)

    image = models.ImageField(upload_to='photos/')

    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    school = models.CharField(max_length=6, choices=SCHOOL_CHOICES, default='CMS')
    grade = models.CharField(max_length=4, choices=GRADE_CHOICES, default='1')
    subject = models.CharField(max_length=20, choices=SUBJECT_CHOICES, default='English')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='HW')
    dateOfAssignment = models.DateField(default=datetime.date.today)

    tags = TaggableManager() 

    def __str__(self):
        return self.title
    
class Assignment(models.Model):
    
    title = models.CharField(max_length=45)
    
    description = models.CharField(max_length=250)

    created = models.DateTimeField(auto_now_add=True)

    image = models.FileField(upload_to='photos/')

    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    school = models.CharField(max_length=6, choices=SCHOOL_CHOICES, default='CMS')
    grade = models.CharField(max_length=4, choices=GRADE_CHOICES, default='1')
    subject = models.CharField(max_length=20, choices=SUBJECT_CHOICES, default='English')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='HW')
    dateOfAssignment = models.DateField(default=datetime.date.today)

    tags = TaggableManager() 

    def __str__(self):
        return self.title

photoapp/views.py
'''Photo app generic views'''

from django.shortcuts import get_object_or_404, HttpResponse, Http404
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Photo, Assignment
from . import views
from django.views import View
from .pdfcreator import renderPdf


class AllPhotoListView(ListView):
    model = Photo     
    template_name = 'photoapp/alllist.html'
    # context_object_name = 'photos'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = Photo.objects.all()
        context['assignments'] = Assignment.objects.all()
        
        print("context", context)
        return context
    
class MyPhotoListView(ListView):
    model = Photo     
    template_name = 'photoapp/mylist.html'
    # context_object_name = 'photos'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['photos'] = Photo.objects.all().filter(submitter=self.request.user)
        print("context", context)
        return context


class PhotoTagListView(AllPhotoListView): 
    template_name = 'photoapp/taglist.html'
    # Custom function
    def get_tag(self):
        return self.kwargs.get('tag')
    def get_queryset(self):
        return self.model.objects.filter(tags__slug=self.get_tag())
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.get_tag()
        return context
     

class PhotoDetailView(DetailView):
    model = Photo
    template_name = 'photoapp/detail.html'
    context_object_name = 'photo'


class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['title', 'description', 'image', 'tags', 'school', 'grade']
    template_name = 'photoapp/create.html'
    success_url = reverse_lazy('photo:mylist')
    def form_valid(self, form):
        form.instance.submitter = self.request.user
        return super().form_valid(form)


class UserIsSubmitter(UserPassesTestMixin):
    # Custom method
    def get_photo(self):
        return get_object_or_404(Photo, pk=self.kwargs.get('pk'))
    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter
        else:
            raise PermissionDenied('Sorry you are not allowed here')


class PhotoUpdateView(UserIsSubmitter, UpdateView):
    template_name = 'photoapp/update.html'
    model = Photo
    fields = ['title', 'description', 'tags']
    success_url = reverse_lazy('photo:mylist')


class PhotoDeleteView(UserIsSubmitter, DeleteView):
    template_name = 'photoapp/delete.html'
    model = Photo
    success_url = reverse_lazy('photo:mylist')

photoapp/templates/photoapp/alllist.html
{% extends '_base.html' %} 

{% block content %}

<h3>All Photos</h3>

<style>
  .pdfobject-container {
     width: 200px;
     height: 200px;
     border-radius: 10px;
  }
</style>

<br>

<a class="button" href="{% url 'photo:create' %}">Add Button photo</a>

<br>

<div class="col-lg-3 col-md-4 col-xs-6" id="my-container"></div>

<script src="https://unpkg.com/pdfobject"></script>
<script> PDFObject.embed("{{ testfile.pdf }}", "#my-container");</script>

<div class="row">
  {% for photo in photos %}
    <div class="col-lg-3 col-md-4 col-xs-6">
      <a href="{% url 'photo:detail' photo.id %}" class="d-block mb-4 h-100">
        <img src="{{photo.image.url}}" class="img-fluid rounded" alt="{{photo.title}}" style="width:100px;height:100px;" style='border:2px solid #000000' />
       <!-- <p style="margin-bottom:0em;">{{ photo.school }} - {{ photo.grade }}</p>
        <p style="margin-bottom:0em;">{{ photo.subject }} - {{ photo.type }} - on - {{ photo.dateOfAssignment }}</p> -->
      </a>
    </div>
  {% endfor %}

  {% for assignment in assignments %}
    <div class="col-lg-3 col-md-4 col-xs-6">
      <a href="{% url 'photo:detail' assignment.id %}" class="d-block mb-4 h-100">
        <img src="{{assignment.image.url}}" class="img-fluid rounded" alt="{{assignment.title}}" style="width:100px;height:100px;" style='border:2px solid #000000' />
        <p style="margin-bottom:0em;">{{ assignment.school }} - {{ assignment.grade }}</p>
        <p style="margin-bottom:0em;">{{ assignment.subject }} - {{ assignment.type }} - on - {{ assignment.dateOfAssignment }}</p>
      </a>
    </div>
  {% endfor %}
</div>

{% endblock content %}

photoapp/templates/photoapp/create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Add Photo</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Add Photo</button>
  </form>
</div>
{% endblock content %}

photoapp/templates/photoapp/delete.html
{% extends '_base.html' %} 

{% block content %}
<div class="form-group mx-auto">
  <h2 class="text-center">
    You are going to <span class="text-danger">delete</span>: "<i
      >{{ photo }}</i
    >
    "
  </h2>
  <p class="text-center">Are you sure, you want to delete the photo ?</p>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'photo:detail' photo.id %}" class="btn btn-primary"
            >Cancel</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
      <p>This action is irreversible</p>
    </form>
  </div>
</div>

{% endblock content %}

photoapp/templates/photoapp/detail.html
{% extends '_base.html' %} 

{% block content %}
<div class="mx-auto">
  <h1 class="text-center">{{ photo.title }}</h1>
  <p class="text-center fw-light">Uploaded on: {{photo.created}} <br> By {{photo.submitter.username}}</p>
  {% if user == photo.submitter %}
    <p class="text-center">
      <span><a href="{% url 'photo:update' photo.id %}" class="text-primary px-2">Update</a></span>
      <span><a href="{% url 'photo:delete' photo.id %}" class="text-danger px-2">Delete</a></span>
    </p>
  {% endif %}
</div>
<div class="row pb-5">
  <div class="col-md-8">
    <img src="{{photo.image.url}}" alt="" class="img-fluid rounded" style="width:400px;" style='border:2px solid #000000' />
  </div>
  <div class="col-md-4">
    <h4>More about this photo:</h4>
    <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
      {% for tag in photo.tags.all %}
        <li><a href="{% url 'photo:tag' tag.slug %}" class="btn btn-sm list-group-item list-group-item-primary">{{tag.name}}</a></li>
      {% endfor %}
    </ul>
    <p>{{ photo.description }}</p>
  </div>
</div>

<form>
  <input type="text" name = "comment">Add Comment</input>
  <button type = "submit">Submit</button>
</form>

{% endblock content %}

photoapp/templates/photoapp/list.html
{% extends '_base.html' %} 

{% block content %}

<h3>Photos</h3>

<br>

<a class="btn" href="{% url 'photo:create' %}">Add Button photo</a>

<br>

<div class="row">
  {% for photo in photos %}
  
  <div class="col-lg-3 col-md-4 col-xs-6">
    <div class="ui card">
    <a href="{% url 'photo:detail' photo.id %}" class="d-block mb-4 h-100">
      <img src="{{photo.image.url}}" class="img-fluid rounded" alt="{{photo.title}}" style="width:100px;height:100px;" style='border:2px solid #000000' />
    </a>
    <!-- <h5>{{ photo.title }}</h5> -->
    <!-- <h5>{{ photo.school }} - {{ photo.grade }}</h5> -->
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

photoapp/templates/photoapp/mylist.html
{% extends '_base.html' %} 

{% block content %}

<h3>My Photos</h3>

<br>

<a class="button" href="{% url 'photo:create' %}">Add Button photo</a>

<br>

<div class="row">
  {% for photo in photos %}
    <div class="col-lg-3 col-md-4 col-xs-6">
      <a href="{% url 'photo:detail' photo.id %}" class="d-block mb-4 h-100">
        <img src="{{photo.image.url}}" class="img-fluid rounded" alt="{{photo.title}}" style="width:100px;height:100px;" style='border:2px solid #000000' />
      </a>
    </div>
  {% endfor %}
</div>

{% endblock content %}

photoapp/templates/photoapp/pdf.html
<!DOCTYPE html>
<html>
<head>
	<title>Homework Classwork</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body>
	<div class="container">
		<div class="row justify-content-md-center">
	        <div class="col-md-12 cart_info">
		        <div class="ordered-info">
		                <img src="{{ pic1 }}"></img>
                        <img src="{{ pic2 }}"></img>
		        </div>
	        </div>
		</div>
	</div> 
</body>
</html>

photoapp/templates/photoapp/taglist.html
{% extends 'photoapp/list.html' %}

{% block content %}

<div class="alert alert-primary">
    <h2 class="text-center">Photos with the tag {{tag}}</h2>
</div>

{{ block.super }}

{% endblock content %}

photoapp/templates/photoapp/update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Edit photo {{photo}}</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
  </form>
</div>
{% endblock content %}